site_name: El Gouna Church
site_description: Welcome to the official website of El Gouna Church. Serving the community with love and faith.
site_url: https://elgounachurch.github.io/
theme:
  name: material
  language: ar
  icon:
    logo: fontawesome/solid/cross
    favicon: fontawesome/solid/cross
  font:
    text: Cairo
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog:
      post_url_format: "{slug}"
  - tags

  - git-committers:
      enabled: true
      repository: Poula-Git/elgounachurch.github.io
      branch: main
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
      enable_git_follow: false
      enabled: true

